// <auto-generated />
using MicroMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MicroMonitor.Data.Migrations
{
    [DbContext(typeof(MonitorContext))]
    [Migration("20190409183549_AddedService")]
    partial class AddedService
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MicroMonitor.MessageQueueUtils.Storage.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationId")
                        .IsRequired();

                    b.Property<string>("GroupId");

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.HasAlternateKey("ApplicationId");

                    b.ToTable("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
